# Site settings
title: "河南大学计算机生存指北"
description: "河南大学计算机学院和软件学院学生/毕业生共同维护的学习指南"
baseurl: ""
url: "https://cs-survive-henu.github.io"
repository: "CS-Survive-henu/CS-Survive-henu.github.io"

# Author settings
author:
  name: "河南大学计算机学院"
  email: "cs-survive@henu.edu.cn"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins - GitHub Pages支持的插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-optional-front-matter

# Collections
collections:
  wiki:
    output: true
    permalink: /:collection/:name/
  guides:
    output: true
    permalink: /:collection/:name/

# Sass设置
sass:
  style: compressed
  sass_dir: assets/css

# Markdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Navigation
header_pages:
  - index.md
  - wiki.md
  - guides.md
  - about.md

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "河南大学计算机学院"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "wiki"
    values:
      layout: "page"

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - deploy.sh
  - deploy.bat
  - preview.html
  - test.html
  - style-test.md
